### ISSUE TITLE
Mixed enum values when for two distinct enum types in the same file

### ISSUE THREAD

**Issue by orenl** [nikolaydubina/go-enum-encoding#24]
If there are multiple enum types in a single file, the generated code combines all their (string)  names.

It seems that problem is that the `-type` argument is ignored; It's probably related to the comment in the code:
```go
		// TODO: check that type matches
```

Try this file for example:

```go
package main

type Enum1 uint8

//go:generate go-enum-encoding -type=Enum1
const (
    OnePlain Enum1 = iota+1 // json:"one_plain"
)

type Enum2 uint8

//go:generate go-enum-encoding -type=Enum2
const (
    TwoPlain Enum2 = iota+1 // json:"two_plain"
)

func main() {
    println("hello world")
}
```

**Comment by nikolaydubina** [comment]
good point. probably can iterate over enum definition to get first type in sequence.

but interim you got to generate one enum per file. 🤷🏻‍♂️

**Comment by nikolaydubina** [comment]
low-pri, as there is workaround.

**Comment by nikolaydubina** [comment]
> It seems that problem is that the -type argument is ignored; It's probably related to the comment in the code:
> 		// TODO: check that type matches

absolutely. this is because only first var-assignment/const-declaration will have type in AST tree. directly next lines in same var/const block may omit type. 

I did not figure out way to solve this nicely in short amount of code, thus left as one-file per enum for this tool.

@orenl if you are up for challenge, feel free to solve this! 👍🏻
